apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: c3ByaW5nZGV2  # Base64 encoded "springdev"
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded "postgres"
  POSTGRES_PASSWORD: U3FsQDEwMDcxOTk5  # Base64 encoded "Sql@10071999"
